NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    # path("accounts/", include("accounts.urls")),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('articles/', include('news.urls')),
    path('', include('news.urls')),
    path('swagger-ui/', TemplateView.as_view(
       template_name='swagger-ui.html',
       extra_context={'schema_url':'openapi-schema'}
    ), name='swagger-ui'),
]

NewsPaper/news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import*
from django.views.decorators.cache import cache_page
from .forms import create_post
urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
    path('', cache_page(60*1)(NewsPaper.as_view()), name='new_list'),
    path('<int:pk>', cache_page(60*5)(NewsDetail.as_view()), name='new_detail'),
    path('<int:pk>', PostSearch.as_view()),
    path('search/', PostSearch.as_view(), name='new_search'),
    path('create/', PostCreate.as_view(), name='new_create'),

    path('<int:pk>/edit/', PostEdit.as_view(), name='new_edit'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='new_delete'),

    # path('articles/', ArticlesPaper.as_view, name='article_list'),
    path('categories/<int:pk>/', CategoryListView.as_view(), name='category_list'),
    path('subscriptions/', SubscriptionView.as_view(), name='subscriptions'),
    path('subscribe/<int:pk>/', subscribe, name='subscribe'),
    path('<int:pk>/', NewsDetail.as_view(), name='new_detail')
    # path('categories/<int:pk>/subscribers', subscribe_delete, name='subscribe_delete'),
   # path('', IndexView.as_view()),
]

#     path('articles/create/', PostCreateArticles.as_view(), name='post_ar_create'),
#     path('articles/<int:pk>/edit/', PostEdit.as_view(), name='post_ar_edit'),
#     path('articles/<int:pk>/delete/', PostDelete.as_view(), name='post_ar_delete'),

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.validators import MinValueValidator
from django.core.cache import cache
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as lz
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.core.mail import send_mail
from django.conf import settings

class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    rating_user = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get("postRating")
        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')
        self.rating_user = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'




class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='old_categories')  # старое поле
    new_subscribers = models.ManyToManyField(
        User,
        through='Subscription',
        related_name='categories'
    )


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, lz('News')),
        (ARTICLE, lz('Articles')),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dataCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory', verbose_name='Категория')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()
    def dislike(self):
        self.rating -= 1
        self.save()
    def preview(self):
        return self.text[0:123] + "..."

    def __str__(self):
        return f'{self.author.authorUser.username}: {self.title}: {self.categoryType}: {self.postCategory}'

    # def __str__(self):
    #     return f' {self.postCategory.name}'

    # def get_success_url(self):
    #     return reverse('new_create', kwargs={'pk': self.kwargs['pk']})
    def get_absolute_url(self):
        return reverse('new_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'product-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его

class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


    def __str__(self):
        return f'{self.postThrough}: {self.categoryThrough}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dataCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.commentPost}: {self.commentUser}: {self.text}: {self.dataCreation}: {self.rating}'

class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    subscribed = models.BooleanField(default=True)
    date_subscribed = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'category')

@receiver(m2m_changed, sender=Post.postCategory.through)
def notify_subscribers(sender, instance, action, **kwargs):
    if action == "post_add":
        # Получаем все категории поста
        for category in instance.postCategory.all():
            # Получаем всех подписчиков через промежуточную модель
            subscriptions = Subscription.objects.filter(category=category, subscribed=True)
            for subscription in subscriptions:
                send_mail(
                    subject=f'Новая публикация в категории {category.name}',
                    message=f'Добавлена новая публикация: "{instance.title}"\n\n'
                           f'Читать: http://127.0.0.1:8000{instance.get_absolute_url()}',
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[subscription.user.email],
                    fail_silently=True,
                )

NewsPaper/news/forms.py
from django import forms
from .models import Post
from django.shortcuts import render
from django.http import*
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
# from django.utils.translation import gettext as _


class PostForm(forms.ModelForm):
   class Meta:
       model = Post
       fields = [
            'author',
            'categoryType',
            'postCategory',
            'title',
            'text',
       ]
       labels = {
           'author': _('author'),
           'categoryType': _('categoryType'),
           'postCategory': _('postCategory'),
           'title': _('title'),
           'text': _('text'),
       }

def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/news')

    form = PostForm()

    return render(request, 'create.html', {'form': form})

# def create_edit(request):
#
#     pass

#
# def create_delete(request):
#     pass
# class PostForm(forms.Form):
#     author = forms.CharField(label='Name')
#     categoryType = forms.CharField(label='Description')
#     title = forms.IntegerField(label='Quantity')
#     postCategory = forms.ModelChoiceField(
#         label='Category', queryset=Category.objects.all(),
#     )
#     text = forms.FloatField(label='Price')

NewsPaper/news/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import*
from .filters import PostFilter
from datetime import datetime, timedelta
from django.views.generic import FormView, CreateView, UpdateView, DeleteView, View
from .forms import PostForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
import logging
from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy
from django.utils import timezone
from django.shortcuts import redirect


import pytz #  импортируем стандартный модуль для работы с часовыми поясами


logger = logging.getLogger(__name__)


# from .tasks import hello, printer
from django.core.mail import send_mail
from pprint import pprint

# class IndexView(View):
#     def get(self, request):
#         printer.apply_async([10],
#                             eta = datetime.now() + timedelta(seconds=5))
#         hello.delay()
#         return HttpResponse('Hello!')

class NewsPaper(ListView):
    # queryset = Post.objects.filter(rating__lt=20.0).values('author')

    model = Post
    # ordering = "categoryType"
    # queryset = Post.objects.get('NW')


    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 10




    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs


    def get_context_data(self, **kwargs):
        current_time = timezone.localtime(timezone.now())
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        context['current_time'] = current_time
        context['timezones'] = pytz.common_timezones
        # pprint(context)
        return context

    # def set_timezone(self, request):
    #     if request.method == 'POST':
    #         request.session['django_timezone'] = request.POST['timezone']
    #         return redirect('/')
    #     else:
    #         return render(request, 'news.html', {'timezones': pytz.common_timezones})
    def post(self, request):
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/')

    def pageNotFound(request, exception):
        return HttpResponseNotFound('<h1>Страница не найдена </h1>')



class ArticlesPaper(ListView):
    queryset = Post.objects.filter(categoryType='AR')
    model = Post
    # ordering = "categoryType"
    # queryset = Post.objects.get('NW')


    template_name = 'articles.html'
    context_object_name = 'articl'
    paginate_by = 10

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     self.filterset = PostFilter(self.request.GET, queryset)
    #     return self.filterset.qs
    #
    #
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['filterset'] = self.filterset
    #     # context['time_now'] = datetime.utcnow()
    #     # context['next_sale'] = None
    #     # pprint(context)
    #     return context

class NewsDetail(DetailView):
    # Модель всё та же, но мы хотим получать информацию по отдельному
    model = Post

    template_name = 'news_detail.html'
    # Название объекта, в котором будет выбранный пользователем
    context_object_name = 'new_detail'

class PostSearch(ListView):

    model = Post
    # ordering = ['-date']
    template_name = 'search.html'
    context_object_name = 'search'
    paginate_by = 10
    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs
    def get_context_data(self, **kwargs):
        current_time = timezone.localtime(timezone.now())
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        context['current_time'] = timezone.now()
        context['timezones'] = pytz.common_timezones
        # datetime.utcnow()
        return context

    def post(self, request):
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/search')


class PostCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    # Указываем нашу разработанную форму
    form_class = PostForm
    # модель товаров
    model = Post
    # и новый шаблон, в котором используется форма.
    template_name = 'create.html'

    # def form_valid(self, form):
    #     categoryType = form.save(commit=False)
    #     categoryType.name = 'Новость'
    #     return super().form_valid(form)


class PostEdit(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'create.html'

class PostDelete(PermissionRequiredMixin,DeleteView):
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'delete.html'
    context_object_name = 'news'
    success_url = reverse_lazy('new_list')

class ProtectedView(LoginRequiredMixin, TemplateView):
    raise_exception = True
    template_name = 'prodected_page.html'

class CategoryListView(ListView):

    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_news_list'

    def get_queryset(self):
        self.postCategory = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(postCategory=self.postCategory).order_by('-dataCreation')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.postCategory.subscribers.all()
        context['category'] = self.postCategory
        return context


@login_required
def subscribe(request, pk):
    category = get_object_or_404(Category, id=pk)

    if request.method == 'POST':
        action = request.POST.get('action', 'subscribe')

        if action == 'subscribe':
            Subscription.objects.get_or_create(
                user=request.user,
                category=category,
                defaults={'subscribed': True}
            )
        elif action == 'unsubscribe':
            Subscription.objects.filter(
                user=request.user,
                category=category
            ).update(subscribed=False)

    return redirect('subscriptions')

class SubscriptionView(LoginRequiredMixin, ListView):
    model = Subscription
    template_name = 'subscribtions.html'  # Указываем явный путь к шаблону
    context_object_name = 'subscriptions'

    def get_queryset(self):
        return Subscription.objects.filter(user=self.request.user, subscribed=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_categories'] = Category.objects.all()
        return context

# @login_required
# def subscribe_delete(request, pk):
#     user = request.user
#     category = Category.objects.get(id=pk)
#     category.subscribers.remove(user)
#
#     message = 'Вы отписались от: '
#     return render(request, 'subscribe_delete.html', {'message': message, 'category': category})
# @login_required
# def upgrade_user(request):
#     user = request.user
#     group = Group.objects.get(name='authors')
#     if not request.user.groups.filter(name='authors').exists():
#         group.user_set.add(user)
#         if not hasattr(user, 'author'):
#             Author.objects.create(
#                 authorUser=User.objects.get(pk=user.id)
#             )
#     return redirect('/')

NewsPaper/templates/articles.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}
{% load custom_filters %}

{% block title %}
Articles
{% endblock title %}

{% block content %}
   <h1>Все статьи:{{article_list|length}}</h1>
   <h3>{{ time_now|date:'M d Y' }}</h3>


   <hr>
   {% if articl %}
       <table>
           <tr>
               <td>Статья</td>
               <td>Дата публикации</td>
               <td>Текст</td>
               <td>Категория</td>
               <td>Рейтинг</td>
           </tr>

           {% for art in articl %}
           <tr>
               <td>{{ art.title }}</td>
               <td>{{ art.dataCreation|date:'d M Y' }}</td>
               <td>{{ art.text|truncatechars:20  }}</td>
               <td>{{ art.postCategory }}</td>
               <td>{{ art.rating }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Статей, нет!</h2>
   {% endif %}
{% endblock content %}

NewsPaper/templates/category_list.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}


{% block title %}
<!--Posts-->
{% endblock title %}


{% block content %}
<h1>Все новости:{{category_news_list|length}}</h1>

    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться?</a> </p>

    {% endif %}

 <h3>{{ time_now|date:'d M Y' }}</h3>
<hr>


   {% if category_news_list %}
       <table>
           <tr>
               <td>Тип</td>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Содержание</td>
               <td>Категория</td>

                {% if perms.news.change_post or perms.news.delete_post %}
                <td>Действия</td>
                {% endif %}


           </tr>
           {% for new in category_news_list %}
           <tr>
               <td>{{ new.get_categoryType_display }}</td>
               <td>{{ new.title }}</td>
               <td>{{ new.dataCreation|date:'d M Y'}}</td>
               <td>{{ new.text|censor|truncatechars:20 }}</td>
               <td>
                   {% for category in new.postCategory.all %}
                        <a href="{% url 'category_list'  category.id %}">{{ category.name }}</a>

                   {% endfor %}
               </td>

                <td>
                    {% if perms.news.change_post %}
                    <a href="{% url 'new_edit' pk=new.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'new_delete' new.id %}">Удалить</a>
                    {% endif %}
                    <a href="{% url 'new_detail' new.id %}">Читать</a>
                </td>
           </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>Новостей, нет!</h2>
   {% endif %}
 {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}
{{ page_obj.number }}
{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
{% endif %}
{% endblock content %}

NewsPaper/templates/create.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block title %}

{% endblock title %}


{% block content %}
<form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">

        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>
<h1>{% trans 'Create post' %}</h1>
<hr>
<form action=""method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">

</form>

{% endblock content %}

NewsPaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Здравствуй! Новые статьи за последнюю неделю!</h2>
<ul>
    {% for post in posts %}
    <li> <a href="{{ link }}{{ post.get_absolute_url }}" >{{ post.title }}</a>  </li>
    {% endfor %}
</ul>
</body>
</html>

NewsPaper/templates/delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}

    <p> Удаляем {{ news.title }} ? </p>

    <input type="submit" value="Delete" />

</form>
{% endblock content %}

NewsPaper/templates/edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}


{% block title %}

{% endblock title %}
{% block content %}
<h1>Редактировать</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}
{% load tz %}

{% block title %}
<!--Posts-->
{% endblock title %}


{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page title</title>

</head>
<body>
    {% for model in Post %}
    <div class="model-class">
        {{ model.name }}

    </div>
    {% endfor %}

<h1>{% trans 'All news' %}:{{news|length}}</h1>





<hr>

    {% if perms.news.add_post %}
    <a href="{% url 'new_create' %}">{% trans 'Add post' %}</a>
    {% endif %}
   {% if news %}
       <table>
           <tr>
               <td>{% trans 'Type' %}</td>
               <td>{% trans 'Header' %}</td>
               <td>{% trans 'Publication date' %}</td>
               <td>{% trans 'Content' %}</td>
               <td>{% trans 'Category' %}</td>

                {% if perms.news.change_post or perms.news.delete_post %}
                <td>{% trans 'Actions' %}</td>
                {% endif %}


           </tr>
           {% for new in news %}
           <tr>
               <td>{{ new.get_categoryType_display }}</td>
               <td>{{ new.title }}</td>
               <td>{{ new.dataCreation|date:'d M Y'}}</td>
               <td>{{ new.text|censor|truncatechars:20 }}</td>
               <td>
                   {% for category in new.postCategory.all %}
                        <a href="{% url 'category_list'  category.id %}">{{ category.name }}</a>

                   {% endfor %}
               </td>

                <td>
                    {% if perms.news.change_post %}
                    <a href="{% url 'new_edit' pk=new.id %}">{% trans 'Change' %}</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'new_delete' new.id %}">{% trans 'Delete' %}</a>
                    {% endif %}
                    <a href="{% url 'new_detail' new.id %}">{% trans 'Read' %}</a>
                </td>
           </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>{% trans 'No, news!' %}</h2>
   {% endif %}
 {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}
{{ page_obj.number }}
{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
{% endif %}
{% endblock content %}
</body>
</html>

NewsPaper/templates/news_detail.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}


{% block content %}
<h1> {{ new_detail.title|censor }} </h1>

<hr>
       {% if new_detail.id %}
              <h3>{{ new_detail.text|censor }}</h3>
       {% else %}
              <h2>новостей, нет!</h2>
       {% endif %}
<hr>

<h5>{{ new_detail.dataCreation|date:'d M Y' }}</h5>
<h6>рейтинг:{{ new_detail.rating }}</h6>

{% endblock content %}

NewsPaper/templates/post_create_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй!Новая <a href="{{ link }}">статья</a> в твоем любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

NewsPaper/templates/prodected_page.html
{% extends 'flatpages/default.html' %}

{% block title %}

{% endblock title %}
{% block content %}
<h1>Редактировать</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %}



{% block title %}

{% endblock title %}


{% block content %}
       <h1 class="text-center">{{ message }} {{ category.name }}</h1>

{% endblock content %}

NewsPaper/templates/subscribtions.html
{% extends 'flatpages/default.html' %}
{% block content %}
<h1>Мои подписки</h1>

<h2>Доступные категории</h2>
<ul>
    {% for category in all_categories %}
    <li>
        {{ category.name }}
        <form method="post" action="{% url 'subscribe' category.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-success">Подписаться</button>
        </form>
    </li>
    {% endfor %}
</ul>

<h2>Текущие подписки</h2>
<ul>
    {% for subscription in subscriptions %}
    <li>
        {{ subscription.category.name }} (с {{ subscription.date_subscribed|date:"d.m.Y" }})
        <form method="post" action="{% url 'subscribe' subscription.category.id %}">
            {% csrf_token %}
            <input type="hidden" name="action" value="unsubscribe">
            <button type="submit" class="btn btn-sm btn-danger">Отписаться</button>
        </form>
    </li>
    {% empty %}
    <li>У вас нет активных подписок</li>
    {% endfor %}
</ul>
{% endblock %}

NewsPaper/templates/swagger-ui.html
<!DOCTYPE html>
<html>
 <head>
   <title>Swagger</title>
   <meta
charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
 </head>
 <body>
   <div id="swagger-ui"></div>
   <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
   <script>
   const ui = SwaggerUIBundle({
       url: "//static/openapi-schema.yml",
       dom_id: '#swagger-ui',
       presets: [
         SwaggerUIBundle.presets.apis,
         SwaggerUIBundle.SwaggerUIStandalonePreset
       ],
       layout: "BaseLayout",
       requestInterceptor: (request) => {
         request.headers['X-CSRFToken'] = "{{ csrf_token }}"
         return request;
       }
     })
   </script>
 </body>
</html>